# Generated by Django 4.1 on 2022-09-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('efirstname', models.CharField(max_length=60)),
                ('elastname', models.CharField(max_length=60)),
                ('esal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ebranch', models.CharField(max_length=60)),
                ('edepartment', models.CharField(max_length=60)),
                ('eproject', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
