# Generated by Django 4.1.1 on 2022-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=45)),
                ('erole', models.CharField(max_length=45)),
                ('edept', models.CharField(max_length=45)),
            ],
        ),
    ]
