# Generated by Django 4.1.1 on 2022-09-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employe',
        ),
    ]
