# Generated by Django 4.1 on 2022-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=20)),
                ('es', models.DecimalField(decimal_places=2, max_digits=20)),
                ('br', models.CharField(max_length=30)),
                ('bd', models.DateField()),
            ],
        ),
    ]
