# Generated by Django 4.1.1 on 2022-09-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolement',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='enrolement',
            name='employe',
        ),
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='employe',
        ),
        migrations.DeleteModel(
            name='enrolement',
        ),
    ]
