# Generated by Django 4.1.1 on 2022-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
