# Generated by Django 4.1.1 on 2022-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='pbgp', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='parimi', max_length=60),
        ),
    ]
